version: '3.9'
services:
  db:
    image: mysql:latest
    container_name: mysql-produto
    environment:
      MYSQL_ROOT_PASSWORD: admin
#      MYSQL_DATABASE: msproduto

    ports:
      - "3307:3306"
    volumes:
#      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

#  dbteste:
#    image: mysql:latest
#    container_name: mysql-produto-test
#    environment:
#      MYSQL_ROOT_PASSWORD: admin
#      MYSQL_DATABASE: msprodutotest
#
#    ports:
#      - "3309:3308"
#    volumes:
#      - db_test_data:/var/lib/mysql

volumes:
  db_data:
#  db_test_data:




